### ISSUE TITLE
Unable to extract used packages info.

### ISSUE THREAD

**Issue by Alvish0407** [anasfik/flutter-spy#2]
I was able to extract assets (json, photos) of the used packages but not the list of packages.

**Comment by anasfik** [comment]
Hi,

can you share with me what it outputs, and if the app is built by you, can you tell the version of Flutter you used.

**Comment by Alvish0407** [comment]
I used v3.16.0

**Comment by Alvish0407** [comment]
I'm trying to decompile it but unable to do now. facing this error.


```shell
/.flutter-spy/lib/decompile: line 13: -d: command not found
```

**Comment by anasfik** [comment]
if you do run `which jadx` command, do you get it showing the jadx binary path?

**Comment by Alvish0407** [comment]
Ohhh Sorry ! You are right. I had removed brew directory so deleted with that.

Even though It showed ```Jadx is installed.``` So, I thought It must be installed already.
