### ISSUE TITLE
Help: Jadx not found

### ISSUE THREAD

**Issue by dev-vickie** [anasfik/flutter-spy#4]
While installing Jadx in Ubuntu 22.04.3 LTS,the error shows no such package is found.

![image](https://github.com/anasfik/flutter-spy/assets/56781148/be64603a-26c9-4786-9ad1-ef9cb975262b)

I have also tried some options from [here](https://operavps.com/docs/fix-unable-to-locate-package-error-on-ubuntu/). I therefore can't get past the prerequisites.

**Comment by TheDauntless** [comment]
As an alternative to apt install, download from the [Jadx repo](https://github.com/skylot/jadx/releases) and make sure the jadx command is available on your path.

**Comment by anasfik** [comment]
@TheDauntless thank you, this should resolve your issue @dev-vickie.
